<a href="https://colab.research.google.com/github/sandyreda898-oss/Smart-Agricultural-Water-Management/blob/main/weather_soil_water_modeling/notebooks/02_soil_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os

repo_path = "/content/Smart-Agricultural-Water-Management"

if not os.path.exists(repo_path):
    !git clone https://github.com/sandyreda898-oss/Smart-Agricultural-Water-Management.git
else:
    print("Repository already exists. Using the current copy.")

Cloning into 'Smart-Agricultural-Water-Management'...
remote: Enumerating objects: 648, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 648 (delta 19), reused 0 (delta 0), pack-reused 562 (from 1)
Receiving objects: 100% (648/648), 131.86 MiB | 9.05 MiB/s, done.
Resolving deltas: 100% (258/258), done.
Updating files: 100% (437/437), done.

In [4]:
import pandas as pd
import numpy as np

base = "/content/Smart-Agricultural-Water-Management/AgriWater/AgriWater_Clean_Data/data/table_exports/"

soil = pd.read_csv(base + "soil_point.csv")
awc = pd.read_csv(base + "soil_awc.csv")
grid = pd.read_csv(base + "grid_point.csv")

In [5]:
print("Soil shape:", soil.shape)
print("AWC shape:", awc.shape)
print("Grid shape:", grid.shape)

Soil shape: (38, 15)
AWC shape: (38, 9)
Grid shape: (38, 5)

In [6]:
soil.head()

,point_id,smu_id,top_depth_cm,bottom_depth_cm,sand_pct,silt_pct,clay_pct,bulk,organic_carbon,ph_water,texture_usda,texture_soter,match_found,soil_data_status,missing_properties
0,grid_0001,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,3.0,F,True,COMPLETE,NaN
1,grid_0002,7001,0.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,True,INCOMPLETE,sand_pct;silt_pct;clay_pct;bulk;organic_carbon...
2,grid_0003,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,3.0,F,True,COMPLETE,NaN
3,grid_0004,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,3.0,F,True,COMPLETE,NaN
4,grid_0005,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,3.0,F,True,COMPLETE,NaN

In [7]:
soil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   point_id            38 non-null     object
 1   smu_id              38 non-null     int64
 2   top_depth_cm        38 non-null     float64
 3   bottom_depth_cm     38 non-null     float64
 4   sand_pct            36 non-null     float64
 5   silt_pct            36 non-null     float64
 6   clay_pct            36 non-null     float64
 7   bulk                36 non-null     float64
 8   organic_carbon      36 non-null     float64
 9   ph_water            36 non-null     float64
 10  texture_usda        36 non-null     float64
 11  texture_soter       38 non-null     object
 12  match_found         38 non-null     bool
 13  soil_data_status    38 non-null     object
 14  missing_properties  2 non-null      object
dtypes: bool(1), float64(9), int64(1), object(4)
memory usage: 4.3+ KB

In [8]:
awc.head()

,point_id,smu_id,awc_smu_mm_per_m,awc_rootable_mm_estimate,root_depth_class,awc_component_status,model_screening_status,awc_use_recommendation,review_status
0,grid_0001,16413,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
1,grid_0002,7001,0.0,0.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,EXCLUDE_NON_SOIL_MAPPING,EXCLUDE,EXCLUDE_NON_SOIL_MAPPING
2,grid_0003,16413,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
3,grid_0004,16413,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
4,grid_0005,16413,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS

In [9]:
awc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   point_id                  38 non-null     object
 1   smu_id                    38 non-null     int64
 2   awc_smu_mm_per_m          38 non-null     float64
 3   awc_rootable_mm_estimate  38 non-null     float64
 4   root_depth_class          38 non-null     int64
 5   awc_component_status      38 non-null     object
 6   model_screening_status    38 non-null     object
 7   awc_use_recommendation    38 non-null     object
 8   review_status             38 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 2.8+ KB

In [10]:
soil.isnull().sum()

point_id               0
smu_id                 0
top_depth_cm           0
bottom_depth_cm        0
sand_pct               2
silt_pct               2
clay_pct               2
bulk                   2
organic_carbon         2
ph_water               2
texture_usda           2
texture_soter          0
match_found            0
soil_data_status       0
missing_properties    36
dtype: int64

In [11]:
awc.isnull().sum()

point_id                    0
smu_id                      0
awc_smu_mm_per_m            0
awc_rootable_mm_estimate    0
root_depth_class            0
awc_component_status        0
model_screening_status      0
awc_use_recommendation      0
review_status               0
dtype: int64

In [12]:
print("Soil duplicate rows:", soil.duplicated().sum())
print("AWC duplicate rows:", awc.duplicated().sum())

print(
    "Duplicate soil point IDs:",
    soil["point_id"].duplicated().sum())

print(
    "Duplicate AWC point IDs:",
    awc["point_id"].duplicated().sum())

Soil duplicate rows: 0
AWC duplicate rows: 0
Duplicate soil point IDs: 0
Duplicate AWC point IDs: 0

In [13]:
soil["soil_data_status"].value_counts()

soil_data_status
COMPLETE                      36
INCOMPLETE                     1
INCOMPLETE_NODATA_SENTINEL     1
Name: count, dtype: int64

In [14]:
soil[
    soil["missing_properties"].notna()][[
        "point_id",
        "soil_data_status",
        "missing_properties"]]

,point_id,soil_data_status,missing_properties
1,grid_0002,INCOMPLETE,sand_pct;silt_pct;clay_pct;bulk;organic_carbon...
27,grid_0028,INCOMPLETE_NODATA_SENTINEL,sand_pct;silt_pct;clay_pct;bulk;organic_carbon...

In [15]:
awc["awc_use_recommendation"].value_counts()

awc_use_recommendation
REVIEW_BEFORE_MODEL_USE          19
CANDIDATE_AFTER_SPATIAL_CHECK    17
EXCLUDE                           2
Name: count, dtype: int64

In [16]:
awc[[
        "point_id",
        "awc_smu_mm_per_m",
        "awc_rootable_mm_estimate",
        "model_screening_status",
        "awc_use_recommendation",
        "review_status"]]

,point_id,awc_smu_mm_per_m,awc_rootable_mm_estimate,model_screening_status,awc_use_recommendation,review_status
0,grid_0001,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
1,grid_0002,0.0,0.0,EXCLUDE_NON_SOIL_MAPPING,EXCLUDE,EXCLUDE_NON_SOIL_MAPPING
2,grid_0003,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
3,grid_0004,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
4,grid_0005,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
5,grid_0006,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
6,grid_0007,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
7,grid_0008,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
8,grid_0009,172.0,178.0,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
9,grid_0010,172.0,172.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
10,grid_0011,172.0,172.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
11,grid_0012,172.0,172.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
12,grid_0013,172.0,172.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
13,grid_0014,172.0,172.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
14,grid_0015,172.0,172.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
15,grid_0016,172.0,172.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
16,grid_0017,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
17,grid_0018,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
18,grid_0019,89.0,89.4,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
19,grid_0020,89.0,89.4,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
20,grid_0021,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
21,grid_0022,89.0,89.4,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
22,grid_0023,89.0,89.4,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
23,grid_0024,90.0,89.8,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
24,grid_0025,90.0,89.8,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
25,grid_0026,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
26,grid_0027,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
27,grid_0028,0.0,0.0,EXCLUDE_WATER_BODY,EXCLUDE,EXCLUDE_WATER_BODY
28,grid_0029,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
29,grid_0030,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
30,grid_0031,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
31,grid_0032,89.0,89.4,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
32,grid_0033,90.0,89.8,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
33,grid_0034,90.0,89.8,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
34,grid_0035,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
35,grid_0036,89.0,89.0,PROVISIONAL_NOT_FIELD_VALIDATED,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED
36,grid_0037,90.0,89.8,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
37,grid_0038,90.0,89.8,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS

In [17]:
print("Soil points:", soil["point_id"].nunique())
print("AWC points:", awc["point_id"].nunique())
print("Grid points:", grid["point_id"].nunique())

print(
    "Soil points missing from grid:",
    set(soil["point_id"]) - set(grid["point_id"]))

print(
    "AWC points missing from grid:",
    set(awc["point_id"]) - set(grid["point_id"]))

Soil points: 38
AWC points: 38
Grid points: 38
Soil points missing from grid: set()
AWC points missing from grid: set()

In [18]:
soil["texture_total_pct"] = (
    soil["sand_pct"] +
    soil["silt_pct"] +
    soil["clay_pct"])

soil[[
        "point_id",
        "sand_pct",
        "silt_pct",
        "clay_pct",
        "texture_total_pct"]].head(10)

    point_id  sand_pct  silt_pct  clay_pct  texture_total_pct
0  grid_0001      21.0      24.0      55.0              100.0
1  grid_0002       NaN       NaN       NaN                NaN
2  grid_0003      21.0      24.0      55.0              100.0
3  grid_0004      21.0      24.0      55.0              100.0
4  grid_0005      21.0      24.0      55.0              100.0
5  grid_0006      21.0      24.0      55.0              100.0
6  grid_0007      21.0      24.0      55.0              100.0
7  grid_0008      21.0      24.0      55.0              100.0
8  grid_0009      21.0      24.0      55.0              100.0
9  grid_0010      40.0      40.0      20.0              100.0

In [19]:
soil["texture_total_pct"].describe()

count     36.0
mean     100.0
std        0.0
min      100.0
25%      100.0
50%      100.0
75%      100.0
max      100.0
Name: texture_total_pct, dtype: float64

In [20]:
soil[
    soil["texture_total_pct"].notna() &
    (
        (soil["texture_total_pct"] < 99) |
        (soil["texture_total_pct"] > 101))][
    [
        "point_id",
        "sand_pct",
        "silt_pct",
        "clay_pct",
        "texture_total_pct"
    ]]

Empty DataFrame
Columns: [point_id, sand_pct, silt_pct, clay_pct, texture_total_pct]
Index: []

In [21]:
print(
    "Invalid sand values:",
    ((soil["sand_pct"] < 0) | (soil["sand_pct"] > 100)).sum()
)

print(
    "Invalid silt values:",
    ((soil["silt_pct"] < 0) | (soil["silt_pct"] > 100)).sum()
)

print(
    "Invalid clay values:",
    ((soil["clay_pct"] < 0) | (soil["clay_pct"] > 100)).sum()
)

print(
    "Invalid pH values:",
    ((soil["ph_water"] < 0) | (soil["ph_water"] > 14)).sum()
)

print(
    "Invalid depth records:",
    (soil["top_depth_cm"] >= soil["bottom_depth_cm"]).sum()
)

Invalid sand values: 0
Invalid silt values: 0
Invalid clay values: 0
Invalid pH values: 0
Invalid depth records: 0

In [22]:
soil_prepared = soil.merge(
    awc,
    on=["point_id", "smu_id"],
    how="left",
    validate="one_to_one")

print("Merged shape:", soil_prepared.shape)

soil_prepared.head()

Merged shape: (38, 23)

,point_id,smu_id,top_depth_cm,bottom_depth_cm,sand_pct,silt_pct,clay_pct,bulk,organic_carbon,ph_water,...,soil_data_status,missing_properties,texture_total_pct,awc_smu_mm_per_m,awc_rootable_mm_estimate,root_depth_class,awc_component_status,model_screening_status,awc_use_recommendation,review_status
0,grid_0001,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,COMPLETE,NaN,100.0,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
1,grid_0002,7001,0.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,...,INCOMPLETE,sand_pct;silt_pct;clay_pct;bulk;organic_carbon...,NaN,0.0,0.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,EXCLUDE_NON_SOIL_MAPPING,EXCLUDE,EXCLUDE_NON_SOIL_MAPPING
2,grid_0003,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,COMPLETE,NaN,100.0,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
3,grid_0004,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,COMPLETE,NaN,100.0,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS
4,grid_0005,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,COMPLETE,NaN,100.0,172.0,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS

In [23]:
soil_prepared = soil_prepared.merge(
    grid,
    on="point_id",
    how="left",
    validate="one_to_one")

print("Final prepared shape:", soil_prepared.shape)

soil_prepared.head()

Final prepared shape: (38, 27)

,point_id,smu_id,top_depth_cm,bottom_depth_cm,sand_pct,silt_pct,clay_pct,bulk,organic_carbon,ph_water,...,awc_rootable_mm_estimate,root_depth_class,awc_component_status,model_screening_status,awc_use_recommendation,review_status,latitude,longitude,district_id,spatial_support
0,grid_0001,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,31.012854,30.818041,9,gridded estimate
1,grid_0002,7001,0.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,EXCLUDE_NON_SOIL_MAPPING,EXCLUDE,EXCLUDE_NON_SOIL_MAPPING,31.012854,30.918041,9,gridded estimate
2,grid_0003,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,31.012854,31.018041,7,gridded estimate
3,grid_0004,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,31.112854,30.718041,5,gridded estimate
4,grid_0005,16413,0.0,20.0,21.0,24.0,55.0,1.64,0.901,7.3,...,178.0,1,PROVISIONAL_WEIGHTED_ROOTABLE_AWC,PROVISIONAL_NOT_FIELD_VALIDATED,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,31.112854,30.818041,9,gridded estimate

In [24]:
soil_prepared["exclude_from_model"] = (
    soil_prepared["awc_use_recommendation"] == "EXCLUDE")

soil_prepared[
    [
        "point_id",
        "soil_data_status",
        "awc_use_recommendation",
        "review_status",
        "exclude_from_model"]]

,point_id,soil_data_status,awc_use_recommendation,review_status,exclude_from_model
0,grid_0001,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
1,grid_0002,INCOMPLETE,EXCLUDE,EXCLUDE_NON_SOIL_MAPPING,True
2,grid_0003,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
3,grid_0004,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
4,grid_0005,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
5,grid_0006,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
6,grid_0007,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
7,grid_0008,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
8,grid_0009,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
9,grid_0010,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
10,grid_0011,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
11,grid_0012,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
12,grid_0013,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
13,grid_0014,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
14,grid_0015,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
15,grid_0016,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
16,grid_0017,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
17,grid_0018,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
18,grid_0019,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
19,grid_0020,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
20,grid_0021,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
21,grid_0022,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
22,grid_0023,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
23,grid_0024,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
24,grid_0025,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
25,grid_0026,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
26,grid_0027,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
27,grid_0028,INCOMPLETE_NODATA_SENTINEL,EXCLUDE,EXCLUDE_WATER_BODY,True
28,grid_0029,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
29,grid_0030,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
30,grid_0031,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
31,grid_0032,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
32,grid_0033,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
33,grid_0034,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
34,grid_0035,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
35,grid_0036,COMPLETE,CANDIDATE_AFTER_SPATIAL_CHECK,CANDIDATE_NOT_FIELD_VALIDATED,False
36,grid_0037,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False
37,grid_0038,COMPLETE,REVIEW_BEFORE_MODEL_USE,REVIEW_MIXED_COMPONENTS,False

In [25]:
soil_clean = soil_prepared[
    ~soil_prepared["exclude_from_model"]].copy()

print("Prepared soil rows:", len(soil_prepared))
print("Clean soil rows:", len(soil_clean))
print("Excluded rows:", len(soil_prepared) - len(soil_clean))

Prepared soil rows: 38
Clean soil rows: 36
Excluded rows: 2

In [26]:
soil_clean["awc_use_recommendation"].value_counts()

awc_use_recommendation
REVIEW_BEFORE_MODEL_USE          19
CANDIDATE_AFTER_SPATIAL_CHECK    17
Name: count, dtype: int64

In [27]:
soil_clean[
    soil_clean["point_id"].isin(
        ["grid_0002", "grid_0028"])]

Empty DataFrame
Columns: [point_id, smu_id, top_depth_cm, bottom_depth_cm, sand_pct, silt_pct, clay_pct, bulk, organic_carbon, ph_water, texture_usda, texture_soter, match_found, soil_data_status, missing_properties, texture_total_pct, awc_smu_mm_per_m, awc_rootable_mm_estimate, root_depth_class, awc_component_status, model_screening_status, awc_use_recommendation, review_status, latitude, longitude, district_id, spatial_support, exclude_from_model]
Index: []

[0 rows x 28 columns]

In [28]:
prepared_output_path = (
    "/content/Smart-Agricultural-Water-Management/"
    "weather_soil_water_modeling/"
    "data/processed/soil_prepared.csv")

soil_prepared.to_csv(
    prepared_output_path,
    index=False)

print("Prepared soil dataset saved.")
print(prepared_output_path)

Prepared soil dataset saved.
/content/Smart-Agricultural-Water-Management/weather_soil_water_modeling/data/processed/soil_prepared.csv

In [29]:
clean_output_path = (
    "/content/Smart-Agricultural-Water-Management/"
    "weather_soil_water_modeling/"
    "data/processed/soil_clean.csv")

soil_clean.to_csv(
    clean_output_path,
    index=False)

print("Clean soil dataset saved.")
print(clean_output_path)

Clean soil dataset saved.
/content/Smart-Agricultural-Water-Management/weather_soil_water_modeling/data/processed/soil_clean.csv

In [30]:
import os

print(
    "Prepared exists:",
    os.path.exists(prepared_output_path))

print(
    "Clean exists:",
    os.path.exists(clean_output_path))

Prepared exists: True
Clean exists: True

In [31]:
from google.colab import files

files.download(prepared_output_path)
files.download(clean_output_path)