<a href="https://colab.research.google.com/github/sandyreda898-oss/Smart-Agricultural-Water-Management/blob/main/weather_soil_water_modeling/notebooks/03_rice_crop_parameters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

repo_path = "/content/Smart-Agricultural-Water-Management"

if not os.path.exists(repo_path):
    !git clone https://github.com/sandyreda898-oss/Smart-Agricultural-Water-Management.git
else:
    print("Repository already exists. Using the current copy.")

Cloning into 'Smart-Agricultural-Water-Management'...
remote: Enumerating objects: 682, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 682 (delta 38), reused 0 (delta 0), pack-reused 562 (from 1)
Receiving objects: 100% (682/682), 134.56 MiB | 15.01 MiB/s, done.
Resolving deltas: 100% (277/277), done.
Updating files: 100% (440/440), done.

In [2]:
import pandas as pd
import numpy as np

base = "/content/Smart-Agricultural-Water-Management/AgriWater/AgriWater_Clean_Data/data/table_exports/"

crop_calendar = pd.read_csv(base + "crop_calendar.csv")
crop_water = pd.read_csv(base + "crop_water_parameter.csv")
season = pd.read_csv(base + "season.csv")
rice_variety = pd.read_csv(base + "rice_variety.csv")
rice_variety_reference = pd.read_csv(base + "rice_variety_reference.csv")

In [3]:
print("Crop calendar:", crop_calendar.shape)
print("Crop water parameters:", crop_water.shape)
print("Season:", season.shape)
print("Rice variety:", rice_variety.shape)
print("Rice variety reference:", rice_variety_reference.shape)

Crop calendar: (7, 13)
Crop water parameters: (10, 13)
Season: (7, 3)
Rice variety: (19, 6)
Rice variety reference: (18, 13)

In [4]:
crop_calendar.head()

,calendar_id,season_year,variety_id,growth_stage,season_start,season_end,planting_window,transplanting_window,harvest_window,stage_start_date,stage_end_date,source_url,data_status
0,1,2017,1,whole_season_reference_window,2017-05-10,2017-10-31,2017-05-10 to 2017-05-31,2017-06-05 to 2017-06-21,2017-08-15 to 2017-10-07,2017-05-10,2017-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
1,2,2018,1,whole_season_reference_window,2018-05-10,2018-10-31,2018-05-10 to 2018-05-31,2018-06-05 to 2018-06-21,2018-08-15 to 2018-10-07,2018-05-10,2018-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
2,3,2019,1,whole_season_reference_window,2019-05-10,2019-10-31,2019-05-10 to 2019-05-31,2019-06-05 to 2019-06-21,2019-08-15 to 2019-10-07,2019-05-10,2019-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
3,4,2020,1,whole_season_reference_window,2020-05-10,2020-10-31,2020-05-10 to 2020-05-31,2020-06-05 to 2020-06-21,2020-08-15 to 2020-10-07,2020-05-10,2020-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
4,5,2021,1,whole_season_reference_window,2021-05-10,2021-10-31,2021-05-10 to 2021-05-31,2021-06-05 to 2021-06-21,2021-08-15 to 2021-10-07,2021-05-10,2021-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...

In [5]:
crop_water.head()

,parameter_id,crop,variety_id,growth_stage,kc,parameter_name,parameter_value,unit,valid_conditions,source_url,data_status,value_min,value_max
0,1,rice,NaN,initial,1.05,Kc,1.05,dimensionless,FAO-56 reference for paddy rice under subhumid...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.05,1.05
1,2,rice,NaN,mid_season,1.20,Kc,1.20,dimensionless,FAO-56 standard reference; adjust for local cl...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.20,1.20
2,3,rice,NaN,late_season,NaN,Kc,NaN,dimensionless,"FAO-56 reference range; stored as min/max, not...",https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_RANGE_NOT_LOCALLY_CALIBRATED,0.60,0.90
3,4,rice,NaN,land_preparation,NaN,soil_saturation_requirement,200.00,mm,General FAO manual assumption; not a local fie...,https://www.fao.org/4/s2022e/s2022e08.htm,LITERATURE_ASSUMPTION_REQUIRES_LOCAL_VALIDATION,200.00,200.00
4,5,rice,NaN,growing_season,NaN,seepage_percolation_rate,NaN,mm/day,General FAO literature range; stored as min/ma...,https://www.fao.org/4/s2022e/s2022e08.htm,LITERATURE_RANGE_REQUIRES_LOCAL_VALIDATION,4.00,8.00

In [6]:
season.head()

   season_year  start_date    end_date
0         2017  2017-05-10  2017-10-31
1         2018  2018-05-10  2018-10-31
2         2019  2019-05-10  2019-10-31
3         2020  2020-05-10  2020-10-31
4         2021  2021-05-10  2021-10-31

In [7]:
rice_variety.head()

,variety_id,name_en,name_ar,season_length_days,source_url,data_status
0,1,NOT_SPECIFIED,NaN,NaN,NaN,PLACEHOLDER_FOR_REGIONAL_REFERENCE_ROWS
1,2,Sakha 101,سخا 101,145.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
2,3,Sakha 102,سخا 102,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
3,4,Sakha 103,سخا 103,120.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
4,5,Sakha 104,سخا 104,135.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE

In [8]:
rice_variety_reference.head()

,variety_id,expected_yield_min_ton_ha,expected_yield_max_ton_ha,grain_type,quality_note,plant_type_note,lodging_note,disease_note,soil_suitability,temperature_min_c,temperature_max_c,source_url,data_status
0,2,9.6,12.0,Japanese broad-grain,High quality,Short-stem,NaN,Blast sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
1,3,8.4,10.0,Japanese broad-grain,High quality,Long-stem,Prone to lodging,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
2,4,9.6,10.5,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
3,5,9.6,10.8,Japanese broad-grain,High quality,Long-stem,Prone to lodging,Blast sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
4,6,9.6,10.8,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE

In [9]:
print("CROP CALENDAR")
print(crop_calendar.columns.tolist())

print("\nCROP WATER PARAMETERS")
print(crop_water.columns.tolist())

print("\nSEASON")
print(season.columns.tolist())

print("\nRICE VARIETY")
print(rice_variety.columns.tolist())

print("\nRICE VARIETY REFERENCE")
print(rice_variety_reference.columns.tolist())

CROP CALENDAR
['calendar_id', 'season_year', 'variety_id', 'growth_stage', 'season_start', 'season_end', 'planting_window', 'transplanting_window', 'harvest_window', 'stage_start_date', 'stage_end_date', 'source_url', 'data_status']

CROP WATER PARAMETERS
['parameter_id', 'crop', 'variety_id', 'growth_stage', 'kc', 'parameter_name', 'parameter_value', 'unit', 'valid_conditions', 'source_url', 'data_status', 'value_min', 'value_max']

SEASON
['season_year', 'start_date', 'end_date']

RICE VARIETY
['variety_id', 'name_en', 'name_ar', 'season_length_days', 'source_url', 'data_status']

RICE VARIETY REFERENCE
['variety_id', 'expected_yield_min_ton_ha', 'expected_yield_max_ton_ha', 'grain_type', 'quality_note', 'plant_type_note', 'lodging_note', 'disease_note', 'soil_suitability', 'temperature_min_c', 'temperature_max_c', 'source_url', 'data_status']

In [10]:
print("=== CROP CALENDAR ===")
crop_calendar.info()

print("\n=== CROP WATER ===")
crop_water.info()

print("\n=== SEASON ===")
season.info()

print("\n=== RICE VARIETY ===")
rice_variety.info()

print("\n=== RICE VARIETY REFERENCE ===")
rice_variety_reference.info()

=== CROP CALENDAR ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   calendar_id           7 non-null      int64
 1   season_year           7 non-null      int64
 2   variety_id            7 non-null      int64
 3   growth_stage          7 non-null      object
 4   season_start          7 non-null      object
 5   season_end            7 non-null      object
 6   planting_window       7 non-null      object
 7   transplanting_window  7 non-null      object
 8   harvest_window        7 non-null      object
 9   stage_start_date      7 non-null      object
 10  stage_end_date        7 non-null      object
 11  source_url            7 non-null      object
 12  data_status           7 non-null      object
dtypes: int64(3), object(10)
memory usage: 860.0+ bytes

=== CROP WATER ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   parameter_id      10 non-null     int64
 1   crop              10 non-null     object
 2   variety_id        0 non-null      float64
 3   growth_stage      10 non-null     object
 4   kc                2 non-null      float64
 5   parameter_name    10 non-null     object
 6   parameter_value   8 non-null      float64
 7   unit              10 non-null     object
 8   valid_conditions  10 non-null     object
 9   source_url        10 non-null     object
 10  data_status       10 non-null     object
 11  value_min         10 non-null     float64
 12  value_max         10 non-null     float64
dtypes: float64(5), int64(1), object(7)
memory usage: 1.1+ KB

=== SEASON ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   season_year  7 non-null      int64
 1   start_date   7 non-null      object
 2   end_date     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

=== RICE VARIETY ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   variety_id          19 non-null     int64
 1   name_en             19 non-null     object
 2   name_ar             18 non-null     object
 3   season_length_days  17 non-null     float64
 4   source_url          18 non-null     object
 5   data_status         19 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.0+ KB

=== RICE VARIETY REFERENCE ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   variety_id                 18 non-null     int64
 1   expected_yield_min_ton_ha  17 non-null     float64
 2   expected_yield_max_ton_ha  17 non-null     float64
 3   grain_type                 17 non-null     object
 4   quality_note               17 non-null     object
 5   plant_type_note            17 non-null     object
 6   lodging_note               2 non-null      object
 7   disease_note               17 non-null     object
 8   soil_suitability           17 non-null     object
 9   temperature_min_c          18 non-null     float64
 10  temperature_max_c          18 non-null     float64
 11  source_url                 18 non-null     object
 12  data_status                18 non-null     object
dtypes: float64(4), int64(1), object(8)
memory usage: 2.0+ KB

In [11]:
datasets = {
    "crop_calendar": crop_calendar,
    "crop_water": crop_water,
    "season": season,
    "rice_variety": rice_variety,
    "rice_variety_reference": rice_variety_reference
}

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

crop_calendar
calendar_id             0
season_year             0
variety_id              0
growth_stage            0
season_start            0
season_end              0
planting_window         0
transplanting_window    0
harvest_window          0
stage_start_date        0
stage_end_date          0
source_url              0
data_status             0
dtype: int64

crop_water
parameter_id         0
crop                 0
variety_id          10
growth_stage         0
kc                   8
parameter_name       0
parameter_value      2
unit                 0
valid_conditions     0
source_url           0
data_status          0
value_min            0
value_max            0
dtype: int64

season
season_year    0
start_date     0
end_date       0
dtype: int64

rice_variety
variety_id            0
name_en               0
name_ar               1
season_length_days    2
source_url            1
data_status           0
dtype: int64

rice_variety_reference
variety_id                    0
expected_yield_min_ton_ha     1
expected_yield_max_ton_ha     1
grain_type                    1
quality_note                  1
plant_type_note               1
lodging_note                 16
disease_note                  1
soil_suitability              1
temperature_min_c             0
temperature_max_c             0
source_url                    0
data_status                   0
dtype: int64

In [12]:
for name, df in datasets.items():
    print(
        name,
        "duplicate rows:",
        df.duplicated().sum()
    )

crop_calendar duplicate rows: 0
crop_water duplicate rows: 0
season duplicate rows: 0
rice_variety duplicate rows: 0
rice_variety_reference duplicate rows: 0

In [13]:
crop_calendar

,calendar_id,season_year,variety_id,growth_stage,season_start,season_end,planting_window,transplanting_window,harvest_window,stage_start_date,stage_end_date,source_url,data_status
0,1,2017,1,whole_season_reference_window,2017-05-10,2017-10-31,2017-05-10 to 2017-05-31,2017-06-05 to 2017-06-21,2017-08-15 to 2017-10-07,2017-05-10,2017-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
1,2,2018,1,whole_season_reference_window,2018-05-10,2018-10-31,2018-05-10 to 2018-05-31,2018-06-05 to 2018-06-21,2018-08-15 to 2018-10-07,2018-05-10,2018-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
2,3,2019,1,whole_season_reference_window,2019-05-10,2019-10-31,2019-05-10 to 2019-05-31,2019-06-05 to 2019-06-21,2019-08-15 to 2019-10-07,2019-05-10,2019-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
3,4,2020,1,whole_season_reference_window,2020-05-10,2020-10-31,2020-05-10 to 2020-05-31,2020-06-05 to 2020-06-21,2020-08-15 to 2020-10-07,2020-05-10,2020-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
4,5,2021,1,whole_season_reference_window,2021-05-10,2021-10-31,2021-05-10 to 2021-05-31,2021-06-05 to 2021-06-21,2021-08-15 to 2021-10-07,2021-05-10,2021-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
5,6,2022,1,whole_season_reference_window,2022-05-10,2022-10-31,2022-05-10 to 2022-05-31,2022-06-05 to 2022-06-21,2022-08-15 to 2022-10-07,2022-05-10,2022-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...
6,7,2023,1,whole_season_reference_window,2023-05-10,2023-10-31,2023-05-10 to 2023-05-31,2023-06-05 to 2023-06-21,2023-08-15 to 2023-10-07,2023-05-10,2023-10-31,https://www.researchgate.net/publication/27984...,REGIONAL_REFERENCE_WINDOW_NOT_YEAR_SPECIFIC;tr...

In [14]:
crop_water

,parameter_id,crop,variety_id,growth_stage,kc,parameter_name,parameter_value,unit,valid_conditions,source_url,data_status,value_min,value_max
0,1,rice,NaN,initial,1.05,Kc,1.05,dimensionless,FAO-56 reference for paddy rice under subhumid...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.05,1.05
1,2,rice,NaN,mid_season,1.20,Kc,1.20,dimensionless,FAO-56 standard reference; adjust for local cl...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.20,1.20
2,3,rice,NaN,late_season,NaN,Kc,NaN,dimensionless,"FAO-56 reference range; stored as min/max, not...",https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_RANGE_NOT_LOCALLY_CALIBRATED,0.60,0.90
3,4,rice,NaN,land_preparation,NaN,soil_saturation_requirement,200.00,mm,General FAO manual assumption; not a local fie...,https://www.fao.org/4/s2022e/s2022e08.htm,LITERATURE_ASSUMPTION_REQUIRES_LOCAL_VALIDATION,200.00,200.00
4,5,rice,NaN,growing_season,NaN,seepage_percolation_rate,NaN,mm/day,General FAO literature range; stored as min/ma...,https://www.fao.org/4/s2022e/s2022e08.htm,LITERATURE_RANGE_REQUIRES_LOCAL_VALIDATION,4.00,8.00
5,6,rice,NaN,establishment,NaN,water_layer_establishment,100.00,mm,General FAO manual assumption; actual field wa...,https://www.fao.org/4/s2022e/s2022e08.htm,LITERATURE_ASSUMPTION_REQUIRES_LOCAL_VALIDATION,100.00,100.00
6,7,rice,NaN,initial,NaN,stage_length,30.00,days,FAO-56 Table 11 generic rice (150-day season);...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,30.00,30.00
7,8,rice,NaN,development,NaN,stage_length,30.00,days,FAO-56 Table 11 generic rice (150-day season);...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,30.00,30.00
8,9,rice,NaN,mid_season,NaN,stage_length,60.00,days,FAO-56 Table 11 generic rice (150-day season);...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,60.00,60.00
9,10,rice,NaN,late_season,NaN,stage_length,30.00,days,FAO-56 Table 11 generic rice (150-day season);...,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,30.00,30.00

In [15]:
season

   season_year  start_date    end_date
0         2017  2017-05-10  2017-10-31
1         2018  2018-05-10  2018-10-31
2         2019  2019-05-10  2019-10-31
3         2020  2020-05-10  2020-10-31
4         2021  2021-05-10  2021-10-31
5         2022  2022-05-10  2022-10-31
6         2023  2023-05-10  2023-10-31

In [16]:
rice_variety

,variety_id,name_en,name_ar,season_length_days,source_url,data_status
0,1,NOT_SPECIFIED,NaN,NaN,NaN,PLACEHOLDER_FOR_REGIONAL_REFERENCE_ROWS
1,2,Sakha 101,سخا 101,145.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
2,3,Sakha 102,سخا 102,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
3,4,Sakha 103,سخا 103,120.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
4,5,Sakha 104,سخا 104,135.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
5,6,Sakha 106,سخا 106,128.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
6,7,Giza 177,جيزة 177,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
7,8,Giza 178,جيزة 178,135.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
8,9,Egyptian Hybrid 1,هجين مصر 1,135.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
9,10,Sakha 107,سخا 107,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
10,11,Sakha 108,سخا 108,135.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
11,12,Sakha 109,سخا 109,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_SOURCE_LISTINGS_CONFLICT_YIELD_AND_PLANT_T...
12,13,Giza 179,جيزة 179,120.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
13,14,Giza 183,جيزة 183,120.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
14,15,Sakha 105,سخا 105,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
15,16,Egyptian Jasmine,الياسمين المصري,145.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
16,17,Giza 182,جيزة 182,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
17,18,Sakha Super 300,سخا سوبر 300,NaN,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE...
18,19,Sakha Asmar 1,سخا الأسمر 1,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE

In [17]:
rice_variety_reference

,variety_id,expected_yield_min_ton_ha,expected_yield_max_ton_ha,grain_type,quality_note,plant_type_note,lodging_note,disease_note,soil_suitability,temperature_min_c,temperature_max_c,source_url,data_status
0,2,9.6,12.0,Japanese broad-grain,High quality,Short-stem,NaN,Blast sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
1,3,8.4,10.0,Japanese broad-grain,High quality,Long-stem,Prone to lodging,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
2,4,9.6,10.5,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
3,5,9.6,10.8,Japanese broad-grain,High quality,Long-stem,Prone to lodging,Blast sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
4,6,9.6,10.8,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
5,7,8.4,10.0,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
6,8,9.6,12.0,Indian-Japanese medium-grain,High quality,Short-stem,NaN,Blast resistant,Fertile and salt-affected soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
7,9,11.5,13.0,Indian-Japanese short-grain,High quality,Long-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
8,10,9.5,10.5,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
9,11,9.5,12.0,Japanese broad-grain,High quality,Short-stem,NaN,Blast sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
10,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_SOURCE_LISTINGS_CONFLICT_YIELD_AND_PLANT_T...
11,13,10.8,12.0,Indian-Japanese medium-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile and salt-affected soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
12,14,9.5,12.0,Indian-Japanese medium-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile and salt-affected soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
13,15,9.5,10.7,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
14,16,10.0,10.5,Indian long-grain aromatic,High quality,Long-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
15,17,8.4,10.0,Indian long-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
16,18,8.5,10.5,Japanese broad-grain,High quality,Strong stem; 114 days late planting and 147 da...,NaN,Blast and insect sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE...
17,19,6.8,6.8,Japanese broad black-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE

In [18]:
crop_calendar_clean = crop_calendar.copy()
season_clean = season.copy()

date_columns = [
    "season_start",
    "season_end",
    "stage_start_date",
    "stage_end_date"]

for col in date_columns:
    crop_calendar_clean[col] = pd.to_datetime(
        crop_calendar_clean[col],
        errors="coerce")

season_clean["start_date"] = pd.to_datetime(
    season_clean["start_date"],
    errors="coerce")

season_clean["end_date"] = pd.to_datetime(
    season_clean["end_date"],
    errors="coerce")

print("Invalid crop calendar dates:")
print(crop_calendar_clean[date_columns].isnull().sum())

print("\nInvalid season dates:")
print(season_clean[["start_date", "end_date"]].isnull().sum())

Invalid crop calendar dates:
season_start        0
season_end          0
stage_start_date    0
stage_end_date      0
dtype: int64

Invalid season dates:
start_date    0
end_date      0
dtype: int64

In [19]:
print(
    "Calendar rows where start >= end:",
    (crop_calendar_clean["season_start"] >= crop_calendar_clean["season_end"]).sum())

print(
    "Season rows where start >= end:",
    (season_clean["start_date"] >= season_clean["end_date"]).sum())

print(
    "Calendar years:",
    crop_calendar_clean["season_year"].min(),
    "to",
    crop_calendar_clean["season_year"].max())

print(
    "Season years:",
    season_clean["season_year"].min(),
    "to",
    season_clean["season_year"].max())

Calendar rows where start >= end: 0
Season rows where start >= end: 0
Calendar years: 2017 to 2023
Season years: 2017 to 2023

In [20]:
calendar_season_check = crop_calendar_clean.merge(
    season_clean,
    on="season_year",
    how="left",
    validate="one_to_one"
)

calendar_season_check[
    [
        "season_year",
        "season_start",
        "start_date",
        "season_end",
        "end_date"
    ]
]

   season_year season_start start_date season_end   end_date
0         2017   2017-05-10 2017-05-10 2017-10-31 2017-10-31
1         2018   2018-05-10 2018-05-10 2018-10-31 2018-10-31
2         2019   2019-05-10 2019-05-10 2019-10-31 2019-10-31
3         2020   2020-05-10 2020-05-10 2020-10-31 2020-10-31
4         2021   2021-05-10 2021-05-10 2021-10-31 2021-10-31
5         2022   2022-05-10 2022-05-10 2022-10-31 2022-10-31
6         2023   2023-05-10 2023-05-10 2023-10-31 2023-10-31

In [21]:
print(
    "Start-date mismatches:",
    (
        calendar_season_check["season_start"] !=
        calendar_season_check["start_date"]
    ).sum()
)

print(
    "End-date mismatches:",
    (
        calendar_season_check["season_end"] !=
        calendar_season_check["end_date"]
    ).sum()
)

Start-date mismatches: 0
End-date mismatches: 0

In [22]:
crop_water_clean = crop_water.copy()

crop_water_clean["parameter_scope"] = np.where(
    crop_water_clean["variety_id"].isna(),
    "GENERAL_RICE",
    "VARIETY_SPECIFIC"
)

crop_water_clean["is_range"] = (
    crop_water_clean["value_min"] !=
    crop_water_clean["value_max"]
)

crop_water_clean[
    [
        "parameter_id",
        "growth_stage",
        "parameter_name",
        "parameter_value",
        "kc",
        "value_min",
        "value_max",
        "unit",
        "parameter_scope",
        "is_range"
    ]
]

,parameter_id,growth_stage,parameter_name,parameter_value,kc,value_min,value_max,unit,parameter_scope,is_range
0,1,initial,Kc,1.05,1.05,1.05,1.05,dimensionless,GENERAL_RICE,False
1,2,mid_season,Kc,1.20,1.20,1.20,1.20,dimensionless,GENERAL_RICE,False
2,3,late_season,Kc,NaN,NaN,0.60,0.90,dimensionless,GENERAL_RICE,True
3,4,land_preparation,soil_saturation_requirement,200.00,NaN,200.00,200.00,mm,GENERAL_RICE,False
4,5,growing_season,seepage_percolation_rate,NaN,NaN,4.00,8.00,mm/day,GENERAL_RICE,True
5,6,establishment,water_layer_establishment,100.00,NaN,100.00,100.00,mm,GENERAL_RICE,False
6,7,initial,stage_length,30.00,NaN,30.00,30.00,days,GENERAL_RICE,False
7,8,development,stage_length,30.00,NaN,30.00,30.00,days,GENERAL_RICE,False
8,9,mid_season,stage_length,60.00,NaN,60.00,60.00,days,GENERAL_RICE,False
9,10,late_season,stage_length,30.00,NaN,30.00,30.00,days,GENERAL_RICE,False

In [23]:
print(
    "Invalid min/max ranges:",
    (
        crop_water_clean["value_min"] >
        crop_water_clean["value_max"]
    ).sum()
)

Invalid min/max ranges: 0

In [24]:
kc_parameters = crop_water_clean[
    crop_water_clean["parameter_name"] == "Kc"
][
    [
        "growth_stage",
        "kc",
        "value_min",
        "value_max",
        "unit",
        "data_status"
    ]
]

kc_parameters

,growth_stage,kc,value_min,value_max,unit,data_status
0,initial,1.05,1.05,1.05,dimensionless,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
1,mid_season,1.20,1.20,1.20,dimensionless,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
2,late_season,NaN,0.60,0.90,dimensionless,FAO_REFERENCE_RANGE_NOT_LOCALLY_CALIBRATED

In [26]:
stage_lengths = crop_water_clean[
    crop_water_clean["parameter_name"] == "stage_length"
][
    [
        "growth_stage",
        "parameter_value",
        "unit",
        "data_status"
    ]
]

stage_lengths

  growth_stage  parameter_value  unit                           data_status
6      initial             30.0  days  FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
7  development             30.0  days  FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
8   mid_season             60.0  days  FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
9  late_season             30.0  days  FAO_REFERENCE_NOT_LOCALLY_CALIBRATED

In [27]:
total_reference_stage_days = stage_lengths[
    "parameter_value"
].sum()

print(
    "Total reference stage length:",
    total_reference_stage_days,
    "days"
)

Total reference stage length: 150.0 days

In [28]:
rice_variety_clean = rice_variety.merge(
    rice_variety_reference,
    on="variety_id",
    how="left",
    validate="one_to_one",
    suffixes=("_variety", "_reference")
)

print("Merged variety rows:", len(rice_variety_clean))

rice_variety_clean.head()

Merged variety rows: 19

,variety_id,name_en,name_ar,season_length_days,source_url_variety,data_status_variety,expected_yield_min_ton_ha,expected_yield_max_ton_ha,grain_type,quality_note,plant_type_note,lodging_note,disease_note,soil_suitability,temperature_min_c,temperature_max_c,source_url_reference,data_status_reference
0,1,NOT_SPECIFIED,NaN,NaN,NaN,PLACEHOLDER_FOR_REGIONAL_REFERENCE_ROWS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Sakha 101,سخا 101,145.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE,9.6,12.0,Japanese broad-grain,High quality,Short-stem,NaN,Blast sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
2,3,Sakha 102,سخا 102,125.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE,8.4,10.0,Japanese broad-grain,High quality,Long-stem,Prone to lodging,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
3,4,Sakha 103,سخا 103,120.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE,9.6,10.5,Japanese broad-grain,High quality,Short-stem,NaN,Blast and insect resistant,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE
4,5,Sakha 104,سخا 104,135.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE,9.6,10.8,Japanese broad-grain,High quality,Long-stem,Prone to lodging,Blast sensitive,Fertile soils,25.0,35.0,https://www.arc.sci.eg/Products/Search/54?Type...,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE

In [29]:
rice_variety_clean[
    rice_variety_clean["source_url_reference"].isna()
][
    [
        "variety_id",
        "name_en",
        "data_status_variety"
    ]
]

   variety_id        name_en                      data_status_variety
0           1  NOT_SPECIFIED  PLACEHOLDER_FOR_REGIONAL_REFERENCE_ROWS

In [30]:
rice_variety_clean[
    rice_variety_clean["season_length_days"].isna()
][
    [
        "variety_id",
        "name_en",
        "season_length_days",
        "data_status_variety"
    ]
]

,variety_id,name_en,season_length_days,data_status_variety
0,1,NOT_SPECIFIED,NaN,PLACEHOLDER_FOR_REGIONAL_REFERENCE_ROWS
17,18,Sakha Super 300,NaN,ARC_CATALOGUE_TRAITS_NOT_LOCAL_YIELD_GUARANTEE...

In [31]:
rice_variety_clean["season_length_days"].describe()

count     17.000000
mean     129.000000
std        7.952987
min      120.000000
25%      125.000000
50%      125.000000
75%      135.000000
max      145.000000
Name: season_length_days, dtype: float64

In [32]:
rice_variety_clean[
    rice_variety_clean["season_length_days"].notna()
][
    [
        "variety_id",
        "name_en",
        "season_length_days"
    ]
].sort_values("season_length_days")

    variety_id            name_en  season_length_days
3            4          Sakha 103               120.0
12          13           Giza 179               120.0
13          14           Giza 183               120.0
2            3          Sakha 102               125.0
9           10          Sakha 107               125.0
11          12          Sakha 109               125.0
6            7           Giza 177               125.0
16          17           Giza 182               125.0
14          15          Sakha 105               125.0
18          19      Sakha Asmar 1               125.0
5            6          Sakha 106               128.0
4            5          Sakha 104               135.0
10          11          Sakha 108               135.0
8            9  Egyptian Hybrid 1               135.0
7            8           Giza 178               135.0
1            2          Sakha 101               145.0
15          16   Egyptian Jasmine               145.0

In [33]:
rice_variety_clean["season_length_available"] = (
    rice_variety_clean["season_length_days"].notna()
)

rice_variety_clean["reference_available"] = (
    rice_variety_clean["source_url_reference"].notna()
)

rice_variety_clean[
    [
        "variety_id",
        "name_en",
        "season_length_available",
        "reference_available"
    ]
]

,variety_id,name_en,season_length_available,reference_available
0,1,NOT_SPECIFIED,False,False
1,2,Sakha 101,True,True
2,3,Sakha 102,True,True
3,4,Sakha 103,True,True
4,5,Sakha 104,True,True
5,6,Sakha 106,True,True
6,7,Giza 177,True,True
7,8,Giza 178,True,True
8,9,Egyptian Hybrid 1,True,True
9,10,Sakha 107,True,True
10,11,Sakha 108,True,True
11,12,Sakha 109,True,True
12,13,Giza 179,True,True
13,14,Giza 183,True,True
14,15,Sakha 105,True,True
15,16,Egyptian Jasmine,True,True
16,17,Giza 182,True,True
17,18,Sakha Super 300,False,True
18,19,Sakha Asmar 1,True,True

In [34]:
stage_reference = stage_lengths[
    ["growth_stage", "parameter_value", "unit", "data_status"]
].copy()

stage_reference = stage_reference.rename(
    columns={
        "parameter_value": "stage_length_days",
        "unit": "stage_length_unit",
        "data_status": "stage_length_status"
    }
)

stage_reference = stage_reference.merge(
    kc_parameters[
        [
            "growth_stage",
            "kc",
            "value_min",
            "value_max",
            "data_status"
        ]
    ],
    on="growth_stage",
    how="left"
)

stage_reference = stage_reference.rename(
    columns={
        "value_min": "kc_min",
        "value_max": "kc_max",
        "data_status": "kc_status"
    }
)

stage_reference

,growth_stage,stage_length_days,stage_length_unit,stage_length_status,kc,kc_min,kc_max,kc_status
0,initial,30.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.05,1.05,1.05,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
1,development,30.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,NaN,NaN,NaN,NaN
2,mid_season,60.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.20,1.20,1.20,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
3,late_season,30.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,NaN,0.60,0.90,FAO_REFERENCE_RANGE_NOT_LOCALLY_CALIBRATED

In [35]:
print("Number of growth stages:", len(stage_reference))

stage_reference

Number of growth stages: 4

,growth_stage,stage_length_days,stage_length_unit,stage_length_status,kc,kc_min,kc_max,kc_status
0,initial,30.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.05,1.05,1.05,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
1,development,30.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,NaN,NaN,NaN,NaN
2,mid_season,60.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,1.20,1.20,1.20,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
3,late_season,30.0,days,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED,NaN,0.60,0.90,FAO_REFERENCE_RANGE_NOT_LOCALLY_CALIBRATED

In [36]:
parameter_sources = (
    crop_water_clean[
        ["source_url", "data_status"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

parameter_sources

,source_url,data_status
0,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_NOT_LOCALLY_CALIBRATED
1,https://www.fao.org/4/x0490e/x0490e0b.htm,FAO_REFERENCE_RANGE_NOT_LOCALLY_CALIBRATED
2,https://www.fao.org/4/s2022e/s2022e08.htm,LITERATURE_ASSUMPTION_REQUIRES_LOCAL_VALIDATION
3,https://www.fao.org/4/s2022e/s2022e08.htm,LITERATURE_RANGE_REQUIRES_LOCAL_VALIDATION

In [37]:
reference_path = (
    "/content/Smart-Agricultural-Water-Management/"
    "weather_soil_water_modeling/data/reference/"
)

crop_calendar_clean.to_csv(
    reference_path + "crop_calendar_reference.csv",
    index=False
)

crop_water_clean.to_csv(
    reference_path + "crop_water_parameters_reference.csv",
    index=False
)

season_clean.to_csv(
    reference_path + "season_reference.csv",
    index=False
)

rice_variety_clean.to_csv(
    reference_path + "rice_variety_reference_prepared.csv",
    index=False
)

stage_reference.to_csv(
    reference_path + "rice_growth_stage_kc_reference.csv",
    index=False
)

parameter_sources.to_csv(
    reference_path + "rice_parameter_sources.csv",
    index=False
)

print("Rice reference datasets saved successfully.")

Rice reference datasets saved successfully.

In [38]:
import os

files_to_check = [
    "crop_calendar_reference.csv",
    "crop_water_parameters_reference.csv",
    "season_reference.csv",
    "rice_variety_reference_prepared.csv",
    "rice_growth_stage_kc_reference.csv",
    "rice_parameter_sources.csv"]

for file in files_to_check:
    path = reference_path + file
    print(file, ":", os.path.exists(path))

crop_calendar_reference.csv : True
crop_water_parameters_reference.csv : True
season_reference.csv : True
rice_variety_reference_prepared.csv : True
rice_growth_stage_kc_reference.csv : True
rice_parameter_sources.csv : True